---
- hosts: localhost
  vars:
    S3_Bucket_Name: just4testing1111
  tasks:
  - name: Create an S3 bucket
    s3_bucket:
      name: "{{ S3_Bucket_Name }}"
      region: us-east-1
      state: present